# Generated by Django 5.0.6 on 2024-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='home_section_images')),
                ('img2', models.ImageField(upload_to='home_section_images')),
                ('img3', models.ImageField(upload_to='home_section_images')),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('para1', models.CharField(max_length=50)),
                ('para2', models.CharField(max_length=50)),
                ('para3', models.CharField(max_length=50)),
            ],
        ),
    ]
