# Generated by Django 5.0.6 on 2024-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0002_alter_homesection_title1_alter_homesection_title2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='img1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='img2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='img3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title3',
            field=models.CharField(max_length=50),
        ),
    ]
