# Generated by Django 5.0.6 on 2024-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0003_alter_homesection_img1_alter_homesection_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='para1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='para2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='para3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title3',
            field=models.CharField(max_length=255),
        ),
    ]
