# Generated by Django 5.0.6 on 2024-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0005_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='para',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='img1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='img2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='img3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='para1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='para2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='para3',
            field=models.TextField(),
        ),
    ]
