# Generated by Django 5.0.6 on 2024-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0006_alter_aboutsection_img_alter_aboutsection_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgimg', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('img1', models.TextField()),
                ('img2', models.TextField()),
                ('img3', models.TextField()),
            ],
        ),
    ]
