# Generated by Django 5.0.6 on 2024-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0007_examplesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='projects_images')),
                ('title', models.CharField(max_length=100)),
                ('para', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='ExampleSection',
        ),
        migrations.DeleteModel(
            name='HomeSection',
        ),
    ]
