# Generated by Django 5.0.6 on 2024-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_app', '0008_projects_delete_aboutsection_delete_examplesection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='projects_images'),
        ),
    ]
